# Python IOError

> 原文:[https://www.educba.com/python-ioerror/](https://www.educba.com/python-ioerror/)

![Python IOError](../Images/5b4c022d85a233780a1098ae894666c5.png)

<noscript><img class="alignnone size-full wp-image-377826" src="../Images/5b4c022d85a233780a1098ae894666c5.png" alt="Python IOError" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError.jpg"/></noscript>

## Python IOError 简介

在 Python 中处理输入和输出操作时，如果我们遇到与 file 相关的错误，代码将抛出 IOError。当我们试图打开一个文件，如果它不存在，将会遇到 IOError。在语句或代码行正确的情况下，它可能会在执行时导致错误。现在，像这样的错误，在程序执行过程中被检测到，被称为异常。通常，当输入输出操作(如 open() file)或方法或简单的打印语句由于 IO 原因(如“磁盘已满”或“找不到文件”)而失败时，会引发 IOError。IOError 类继承自 EnvironmentError。

**语法:**

<small>网页开发、编程语言、软件测试&其他</small>

下面提到的语法是一种标准格式，将使用它来打印错误的发生。

`IOError: [Errno 1] No such file or directory: 'somefile.txt'`

以错误名 IOError 开始，后面是使用 Errno 关键字在单个程序中发生的错误号。解释错误原因的消息，通常没有这样的文件或目录，这意味着我们传入的文件名在位置提及中不可用，或者位置不正确。最后，是我们传递的文件的名称。这有助于我们了解要查找哪个文件或更改其名称。该语法旨在帮助程序员解决错误并继续前进。

### IOError 如何在 Python 中工作？

*   在 Python 程序中，我们有一个打印文件内容的简单操作，我们传递文件名和文件位置的路径。
*   但是如果我们传递的文件在传递的位置不存在，或者文件名被改变了，那么我们要执行的操作就不会发生。
*   这将导致与输入输出相关的误差，即 IOError。
*   因此，基本上，IOError 是一个异常类型的错误，当我们作为参数传入的文件不存在，或者作为不同的名称，或者文件位置路径不正确时，就会发生这种错误。
*   这些原因中任何一个都可能引发 IOError。
*   还有许多其他可能遇到的错误，根据代码的要求，我们已经处理了这些错误。

### Python IOError 示例

下面是提到的例子:

#### 示例#1

代码的基本实现，其中代码将抛出 IOError。我们的第一个程序将有一些文件操作，这将失败，程序将打印错误。

**代码:**

```
import sys
file = open('myfile.txt')
lines = file.readline()
slines = int(lines.strip()) 
```

**说明:**

*   为了解释上面的代码，我们有我们的导入文件。然后我们对一个文件进行三次操作。首先，我们打算传递文件细节并访问它。然后是 readline 方法，它将读取文件的内容，然后是 strip，它将删除句子开头和结尾的字符。
*   我们在这里不打印任何输出，因为我们希望看到错误引发的工作情况。因此，当正确执行上述代码时，输出将是一个错误，具体来说是 IOError。

**输出:**

![Python IOError 1](../Images/46de0bb3c6e9b88734fb23b642129994.png)

<noscript><img class="alignnone wp-image-377479 size-full" src="../Images/46de0bb3c6e9b88734fb23b642129994.png" alt="Python IOError 1" width="773" height="162" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-1.jpg 773w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-1-300x63.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-1-768x161.jpg 768w" sizes="(max-width: 773px) 100vw, 773px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/Python-IOError-1.jpg"/></noscript>

正如您所看到的，输出是预期的。指出错误发生在哪一行，并打印整行代码。这里，我们没有使用任何方法来捕捉这些错误。

#### 实施例 2

在这里，我们将演示如何使用 try except 块捕获 python IOError 或任何其他错误。带有 try except 块的程序代码如下。

**代码:**

```
import sys
def something():
  try:
     file = open ( "filethatdoesnotexist.txt", 'r' )
   except IOError, e:
     print e
print sys.exc_type
something() 
```

**说明:**

*   我们的程序从导入系统文件开始，因为我们将处理输入输出操作。然后我们用某物的名字()定义了第一个函数。
*   在函数内部，我们开始我们的 try 关键字，这意味着从这一点开始的每一件事都将被寻找一个错误。在 out try 中，我们有第一个文件操作，即打开一个文件。
*   我们的预期输出是这样的:没有这样的文件或目录:“filethatdoesnotexist.txt”。

**输出:**

![python IOError 2](../Images/3fdb566a152d99bd19ab4d8a594e29eb.png)

<noscript><img class="alignnone wp-image-377480 size-full" src="../Images/3fdb566a152d99bd19ab4d8a594e29eb.png" alt="python IOError 2" width="819" height="113" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/06/python-IOError-2.jpg 819w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/python-IOError-2-300x41.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/06/python-IOError-2-768x106.jpg 768w" sizes="(max-width: 819px) 100vw, 819px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/06/python-IOError-2.jpg"/></noscript>

正如你所看到的，我们的程序抛出了一个异常，说程序中传递的文件不存在。

### Python 中如何避免 IOError？

*   在任何编程或脚本语言中，完全有可能以一种可以捕捉预期错误的方式编写程序。
*   在执行之前理解代码并包含必要的 catch 异常子句将有助于避免异常。
*   在 Python 中处理异常的一个基本且最简单的方法是实现 catch-all except 子句。
*   像 try 和 except 这样的关键字在这里保存实际值，用于捕捉任何类型的异常。
*   也建议不要在一个程序中使用很多 try except 块。
*   错误是在 try 部分中捕获的，而在 except 部分中处理。
*   此外，我们可以将 finally 与 try except 块一起使用。
*   finally 在这里的主要用途是不管捕捉到或处理了什么错误都执行代码。

### 结论

Python 中的 IOError 是文件名或位置不正确的结果。此错误在多种情况下出现，所有这些情况都可以使用 try except 代码块来处理。我们通过示例看到了错误的工作原理，并看到了如何避免它。实现 try except block 会省去很多辛苦的工作。

### 推荐文章

这是 Python IOError 的指南。这里我们讨论 python 中 IOError 的介绍，以及它是如何与示例代码一起工作的。您也可以看看以下文章，了解更多信息–

1.  [Python 并发](https://www.educba.com/python-concurrency/)
2.  [Python 中的控制语句](https://www.educba.com/control-statements-in-python/)
3.  [Python argparse](https://www.educba.com/python-argparse/)
4.  [Python 中的函数重载](https://www.educba.com/function-overloading-in-python/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>