# Java 并发修改异常

> 原文:[https://www . edu CBA . com/Java-concurrentmodificationexception/](https://www.educba.com/java-concurrentmodificationexception/)

![Java ConcurrentModificationException](../Images/ab8538fc6d4431e6932c381ee58e2af2.png)

<noscript><img class="alignnone size-full wp-image-368905" src="../Images/ab8538fc6d4431e6932c381ee58e2af2.png" alt="Java ConcurrentModificationException" width="900" height="500" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ArrayIndexOutOfBoundsException-1.jpg 900w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ArrayIndexOutOfBoundsException-1-300x167.jpg 300w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ArrayIndexOutOfBoundsException-1-768x427.jpg 768w" sizes="(max-width: 900px) 100vw, 900px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ArrayIndexOutOfBoundsException-1.jpg"/></noscript>

## Java ConcurrentModificationException 简介

Java 编程语言提供了一系列异常处理案例，并发修改异常就是其中之一。当程序中的线程试图修改在当前进程中不具有编辑权限的对象时，发生并发修改异常。简单地说，当我们试图编辑一个当前正被另一个进程使用的对象时，就会出现 ConcurrentModificationException。

一个非常简单的例子是线程正在处理的集合。不允许修改正在处理的集合，因此会引发 ConcurrentModificationException。

<small>网页开发、编程语言、软件测试&其他</small>

**语法:**

下面是异常的最简单语法。ConcurrentModificationException 是 java lang RunTimeException 的一部分，它扩展了它。

```
public class Concurrent Modification Exception
extends Runtime Exception
```

### ConcurrentModificationException 在 Java 中是如何工作的？

我们在 Java 中创建对象时，根据自己的需要设置一些限制和权限，这是可以理解的。但有时，我们试图改变值或修改列表，只是当它在线程中时，这是当 ConcurrentModificationException 出现时，因为该对象已被另一个线程使用，不能编辑或修改。

同样重要的是要知道这个异常并不总是意味着有一个对象正在被同时修改。在单个线程的情况下，如果方法调用正在发生，这在某种程度上违反了对象契约，就会抛出这个异常。

**构造函数:**

ConcurrentModificationException 的一个非常基本的构造函数很简单，如下所示:ConcurrentModificationException()。除了简单的构造函数之外，我们还有以下贡献者，可以根据需要使用:

*   **ConcurrentModificationException(String text message):**带有简单消息的构造函数。
*   **ConcurrentModificationException(String text message，Throwable textcause):** 带有消息和详细原因的构造函数。
*   **ConcurrentModificationException(Throwable text cause):**带原因的构造函数，这里原因可以为空，表示未知。

### Java 并发修改异常的示例

既然我们已经理解了什么是并发修改异常以及它是如何工作的，那么让我们转到实现。我们现在将通过一个例子来理解这个异常；例如，我们将有一个数组列表，随着一些操作，我们将试图修改它，这将导致一个异常。该示例的代码如下:

#### 示例#1

**代码:**

```
import java.awt.List;
import java.util.*;
public class ConcurrentModificationException {
public static void main ( String[] args) {
ArrayList<Integer> Numberlist = new ArrayList<Integer> () ;
Numberlist.add ( 1) ;
Numberlist.add ( 2) ;
Numberlist.add ( 3) ;
Numberlist.add ( 4) ;
Numberlist.add ( 5) ;
Iterator<Integer> it = Numberlist.iterator () ;
while ( it.hasNext () ) {
Integer numbervalue = it.next () ;
System.out.println ( "List Value:" + numbervalue) ;
if ( numbervalue .equals ( 3) )
Numberlist.remove ( numbervalue) ;
}
}
}
```

**代码解释:**从几个导入文件开始，然后类减速和 main 方法。初始化数组列表并添加一个函数来保持添加一个数字；这样，它会在过程中。在下一次添加时，我们打印列表值。但是接下来我们有一个 if 循环，它会寻找一个等于 3 的数，一旦找到 3，它会试图删除这个数，这就是异常会遇到的地方，程序会被终止。名单上不会再有新的东西了。

如果您执行上面的代码没有任何错误，代码将会遇到一个异常。该异常位于 concurrentmodificationexception . main(concurrentmodificationexception . Java:14)。这个异常的原因很明显，我们试图修改一个列表，Numberlist。请参考下面附加的屏幕截图以获得正确的输出:

![Java ConcurrentModificationException-1.1](../Images/7befc192ec59ddb68f5f71a13d637cf9.png)

<noscript><img class="alignnone size-full wp-image-368361" src="../Images/7befc192ec59ddb68f5f71a13d637cf9.png" alt="Java ConcurrentModificationException-1.1" width="583" height="146" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.1.png 583w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.1-300x75.png 300w" sizes="(max-width: 583px) 100vw, 583px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.1.png"/></noscript>

如您所见，程序按照我们的预期执行，print 语句成功执行，直到遇到值 3。程序流在值为 3 时被中断，因为我们有一个 if 循环，它查找等于 3 的值并删除它。但是迭代器已经在进行中，删除 3 的尝试将会失败，这将抛出异常 ConcurrentModificationException。

#### 实施例 2

为了第二个例子的目的，我们将尝试执行一个程序，它将成功地避开并发修改异常。在相同的代码中，如果我们试图在处理过程中修改数组列表，它将捕获 ConcurrentModificationException，程序将被终止。第二个示例的代码如下:

**代码:**

```
import java.util.Iterator;
import java.util.ArrayList;
public class ConcurrentModificationException {
public static void main ( String args[])
{
ArrayList<String> arraylist = new ArrayList<String> ( ) ;
arraylist.add ( "One") ;
arraylist.add ( "Two") ;
arraylist.add ( "Three") ;
arraylist.add ( "Four") ;
try {
System.out.println ( "ArrayList: ") ;
Iterator<String> iteratornew = arraylist.iterator () ;
while ( iteratornew.hasNext ( ) ) {
System.out.print ( iteratornew.next ()
+ ", ");
}
System.out.println ( "\n\n Trying to add an element in between iteration:"
+ arraylist.add ( "Five") ) ;
System.out.println ( "\n Updated ArrayList: \n") ;
iteratornew = arraylist.iterator () ;
while ( iteratornew.hasNext ( ) ) {
System.out.print ( iteratornew.next ()
+ ", ");
}
}
catch ( Exception e) {
System.out.println ( e) ;
}
}
}
```

**代码解释:**类似于前面的程序，我们有需要的文件和方法。我们只是在数组列表中添加了一些元素，它在迭代；我们添加另一个元素，即五。我们将根据最新添加的内容打印更新的列表，其中将包含我们新添加的元素。我们实现了 try-catch 块来捕获异常。如果发生任何异常，它将打印异常。

**输出:**

![Java ConcurrentModificationException-1.2](../Images/a5c886719e80d4914c0a6ab3a488bc0f.png)

<noscript><img class="alignnone size-full wp-image-368362" src="../Images/a5c886719e80d4914c0a6ab3a488bc0f.png" alt="Java ConcurrentModificationException-1.2" width="367" height="140" srcset="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.2.png 367w, https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.2-300x114.png 300w" sizes="(max-width: 367px) 100vw, 367px" data-original-src="https://cdn.educba.com/academy/wp-content/uploads/2020/05/Java-ConcurrentModificationException-1.2.png"/></noscript>

正如您在输出中看到的，第一个数组列表很简单，只有很少的元素。然后在下一行，我们试图在迭代中添加一个元素，这个元素是“Five”。它被成功添加，并为句子打印 true。在下一行中，我们打印一个更新的列表，它包含了五个元素。我们在流程结束后更新了列表；如果我们试图在进程中添加元素，它将抛出 ConcurrentModificationException，程序将停止。

### Java 中如何避免 ConcurrentModificationException？

在不同级别的线程上避免并发修改异常是可能的。为了避免单线程环境中的并发异常，可以从迭代器中移除对象并修改它，使用 remove()。

在多线程环境中，您几乎没有选择，比如将进程中的列表转换为数组，然后处理数组。然后，您还可以将一个同步块放在一个列表上并锁定它。但是不建议锁定列表，因为它可能会限制多线程编程的优势。使用子列表修改列表将不会产生任何结果。在所有避免的方法中，最优选的方法是等到执行完成，然后编辑或修改列表或对象。

### 结论

当一个进程正在使用一个资源，而另一个进程试图编辑或修改它时，将引发异常 ConcurrentModificationException。避免的最简单方法是在迭代后修改列表。列出了许多方法来避免异常，但是建议用小程序来实现它们。

### 推荐文章

这是一个 Java 并发修改异常的指南。在这里我们也讨论一下入门以及它在 java 中是如何工作的？以及不同的示例及其代码实现。您也可以看看以下文章，了解更多信息–

1.  [Java 8 中的可选类](https://www.educba.com/optional-class-in-java-8/)
2.  [禁用 JavaScript](https://www.educba.com/disable-javascript/)
3.  [爪哇的 EJB](https://www.educba.com/ejb-in-java/)
4.  [JavaScript join ()](https://www.educba.com/javascript-join/)

<footer class="entry-footer">

<aside class="sidebar sidebar-primary widget-area" role="complementary" aria-label="Primary Sidebar">Primary Sidebar</aside>

</footer>